FFR/Models/request.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int Id { get; set; }
        public int customer_id { get; set; }
        public int meal_id { get; set; }
        public int center_id { get; set; }
        public Nullable<bool> done { get; set; }
        public Nullable<System.DateTime> reqdate { get; set; }
    
        public virtual center center { get; set; }
        public virtual customer customer { get; set; }
        public virtual meal meal { get; set; }
    }
}

FFR/Controllers/ManagementController.cs
using FFR.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FFR.Controllers
{
    public class ManagementController : Controller
    {
        Database1Entities db = new Database1Entities();
        // GET: Management
        public ActionResult Index()
        {
            if(Session["admin"]==null)return RedirectToAction("access_denied", "Home", null);
            return View();
        }
        [HttpGet]
        public ActionResult Add(FormCollection col)
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            return View();
        }
        [HttpPost]
        public ActionResult Add(category cat)
        {
            if (cat == null) return View();
            List<category> l = (from x in db.categories where x.name == cat.name.Trim() select x).ToList();
            if(l.Count > 0)
            {
                ViewBag.message = "هذا الصنف موجود بالفعل";
                return View();
            }
            cat.name = cat.name.Trim();
            db.categories.Add(cat);
            db.SaveChanges();
            ViewBag.message = "تمت إضافة الصنف";
            return View();
        }
        string unique()
        {
            return DateTime.Now.ToString("dd-MM-yyyy-HH-mm-ss");
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            ViewBag.category_id = new SelectList(db.categories, "Id", "name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase UploadImage,FormCollection col)
        {
            string n = "";
            ViewBag.category_id = new SelectList(db.categories, "Id", "name");
            if (UploadImage.ContentLength > 0)
            {
                string filename = unique() + Path.GetExtension(UploadImage.FileName);
                string folder = Path.Combine(Server.MapPath("~/pics/"), filename);
                UploadImage.SaveAs(folder);
                n = filename;
            }
            else { return View(); }
            string mealname = col[1].Trim();
            List<meal> l = (from x in db.meals where x.name == mealname select x).ToList();
            if(l.Count > 0)
            {
                ViewBag.message = "هنالك وجبة بنفس الاسم" ;
                return View();
            }
            meal m = new meal();
            m.name = col[1].Trim();
            m.picture = n;
            m.price = Convert.ToInt32(col[2].Trim());
            m.discount_price = m.price;
            m.category_id = Convert.ToInt32(col[4].Trim());
            m.discription = col[3].Trim();
            db.meals.Add(m);
            db.SaveChanges();
            ViewBag.message = "تم إضافة الوجبة" ;
            return View();
        }
        public ActionResult delete(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            if (id != null)
            {
               System.IO.File.Delete(Server.MapPath("~/pics/") + (from x in db.meals where x.Id == id select x.picture).FirstOrDefault());
                db.meals.Remove((from x in db.meals where x.Id == id select x).FirstOrDefault());
                db.SaveChanges();
            }
            List<meal> lst = (from x in db.meals select x).ToList();
            return View(lst);

        }
        public ActionResult Del_cat(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            if (id != null)
            {
                db.categories.Remove((from x in db.categories where x.Id == id select x).FirstOrDefault());
                db.SaveChanges();
            }
            List<category> lst = (from x in db.categories select x).ToList();
            return View(lst);

        }

        public ActionResult Edit_list()
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            List<meal>l = (from x in db.meals select x).ToList();
            return View(l);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Session["admin"] == null) return RedirectToAction("login_signup", "Home", null);
            meal m = (from x in db.meals where x.Id == id select x).FirstOrDefault();
            ViewBag.category_id = new SelectList(db.categories, "Id", "name");
            return View(m);
        }
        [HttpPost]
        public ActionResult Edit(int id,meal mel,HttpPostedFileBase UploadImage)
        {
            if(UploadImage == null)
                mel.picture = (from x in db.meals where x.Id == mel.Id select x.picture).FirstOrDefault();
            
            else
            {
                System.IO.File.Delete(Server.MapPath("~/pics/") + (from x in db.meals where x.Id == id select x.picture).FirstOrDefault());
                if (UploadImage.ContentLength > 0)
                {
                    string filename = unique() + Path.GetExtension(UploadImage.FileName);
                    string folder = Path.Combine(Server.MapPath("~/pics/"), filename);
                    UploadImage.SaveAs(folder);
                    mel.picture = filename;
                }
            }
            db.meals.AddOrUpdate(mel);
            db.SaveChanges();
            ViewBag.category_id = new SelectList(db.categories, "Id", "name");
            meal m = (from x in db.meals where x.Id == id select x).FirstOrDefault();
            ViewBag.message = "تم تحديث بيانات الوجبة";
            return View(m);
        }
        public ActionResult delete_offer(int? id)
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            if (id != null)
            {
                meal m = (from x in db.meals where x.Id == id select x).FirstOrDefault();
                m.discount_price = m.price;
                db.meals.AddOrUpdate(m);
                db.SaveChanges();
                
            }
            List<meal> lst = (from x in db.meals where x.price != x.discount_price select x).ToList();
            return View(lst);
        }
        public ActionResult create_offer_list()
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            List<meal> lst = (from x in db.meals where x.price == x.discount_price select x).ToList();
            return View(lst);
        }
        public ActionResult create_offer(int id)
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            meal m = (from x in db.meals where x.Id == id select x).FirstOrDefault();
            return View(m);
        }
        [HttpPost]
        public ActionResult create_offer(int id,meal mel)
        {
            ViewBag.message = "تم انشاء العرض";
            meal nm = (from x in db.meals where x.Id == mel.Id select x).FirstOrDefault();
            nm.discount_price = mel.discount_price;
            db.meals.AddOrUpdate(nm);
            db.SaveChanges();
            meal m = (from x in db.meals where x.Id == id select x).FirstOrDefault();
            return View(m);
        }
        public ActionResult requests(int?id)
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            if (id != null)
            {
                request r = (from x in db.requests where x.Id == id select x).FirstOrDefault();
                r.done = true;
                db.requests.AddOrUpdate(r);
                db.SaveChanges();
                ViewBag.message = "تم تعيينه كمُعَالَجْ";
            }
            List<request> reqs = (from x in db.requests where x.done != true select x).ToList();
            return View(reqs);
        }
        public ActionResult reports_list()
        {
            if (Session["admin"] == null) return RedirectToAction("access_denied", "Home", null);
            return View(db.customers.ToList());
        }
        [HttpPost]
        public ActionResult report(FormCollection col)
        {
            int id = Convert.ToInt32(col.AllKeys[0]);
            ViewBag.favs = (from x in db.favorits where x.customer_id == id select x).ToList();
            ViewBag.reqs = (from x in db.requests where x.customer_id == id select x).ToList();
            customer c = (from x in db.customers where x.Id == id select x).First();
            return View(c);
        }
    }
}

FFR/Views/Management/Create.cshtml
@model FFR.Models.meal

@{
    ViewBag.Title = "إضافة وجبة";
}


<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>إضافة وجبة</h1>
            </div>
        </div>
    </div>
</div>
<div class="stuff-box">
    <div class="container">
        @using (Html.BeginForm("Create", "Management", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal text-right" dir="rtl">
            @if (ViewBag.message != null)
            {
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                @ViewBag.message
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            }
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <p class="control-label col-md-2">اسم الوجبة</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p class="control-label col-md-2">السعر</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p class="control-label col-md-2">الصورة</p>
                <div class="col-md-10">
                    @Html.TextBox("UploadImage", "", new { type = "File", required = "required" })
                    @Html.ValidationMessageFor(model => model.picture, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p class="control-label col-md-2">وصف الوجبة</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.discription, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.discription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p class="control-label col-md-2">اختر الصنف</p>
                <div class="col-md-10">
                    @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control", required = "required" })
                    @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="إضافة" class="btn btn-success" />
                </div>
            </div>
        </div>
        }

        <div dir="rtl" class="text-right">
            @Html.ActionLink("العودة لصفحة الإدارة", "Index")
        </div>
    </div>
</div>

FFR/Views/Management/Del_cat.cshtml
@model IEnumerable<FFR.Models.category>

@{
    ViewBag.Title = "حذف صنف";
}


<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>حذف صنف</h1>
            </div>
        </div>
    </div>
</div>
<div class="stuff-box">
    <div class="container text-right" dir="rtl">

        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>تنويه هام!</h2>
                    <p>عند قيامك بحذف أي صنف سيتم حذف كافة المأكولات المدرجة ضمنه</p>
                </div>
            </div>
        </div>
        <table class="table">
            <tr>
                <th>
                    اسم الصنف
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.ActionLink("حذف", "Del_cat", new { id = item.Id }, new { @class = "btn btn-outline-danger btn-sm" })
                    </td>
                </tr>
            }

        </table>
        <div class="text-right" dir="rtl">
            @Html.ActionLink("العودة لصفحة الإدارة", "Index")
        </div>
    </div>
</div>

FFR/Views/Management/Edit.cshtml
@model FFR.Models.meal

@{
    ViewBag.Title = "تعديل بيانات وجبة";
}

<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>تعديل وجبة</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->
<!-- Start Stuff -->
<div class="stuff-box">
    <div class="container text-right" dir="rtl">
        @using (Html.BeginForm("Edit", "Management", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @if (ViewBag.message != null)
                {
                    <div class="alert alert-info alert-dismissible fade show" role="alert">
                        @ViewBag.message
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    <p class="control-label col-md-2">اسم الوجبة</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="control-label col-md-2">السعر</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="control-label col-md-2">سعر الخصم</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.discount_price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.discount_price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="control-label col-md-2">الصورة</p>
                    <div class="col-md-10">
                        @Html.TextBox("UploadImage", "", new { type = "File" })
                        @Html.ValidationMessageFor(model => model.picture, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="control-label col-md-2">الوصف</p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.discription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.discription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="control-label col-md-2">الصنف</p>
                    <div class="col-md-10">
                        @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="حفظ" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("العودة لقائمة التعديل", "Edit_list")
        </div>
    </div>
</div>

FFR/Views/Management/Index.cshtml
@{
    ViewBag.Title = "الإدارة";
}

<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>الإدارة</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->
<!-- Start Stuff -->
<div class="stuff-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/tdl.png")">
                    </div>
                    <div class="team-content">
                        @Html.ActionLink("استعراض الطلبات", "requests", null, new { @class = "title" })
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/add_meal.jpg")">
                    </div>
                    <div class="team-content">
                        @Html.ActionLink("إضافة وجبة", "Create", null, new { @class = "title" })
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/delete_meal.jpg")">
                    </div>
                    <div class="team-content">
                        @Html.ActionLink("حذف وجبة", "delete", null, new { @class = "title" })
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/edit_meal.jpg")">
                    </div>
                    <div class="team-content">
                        @Html.ActionLink("تعديل وجبة", "edit_list", null, new { @class = "title" })
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/add_category.png")">
                    </div>
                    <div class="team-content">
                        <h3 class="title">@Html.ActionLink("إضافة صنف", "Add", null, new { @class = "title" })</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/delete_category.jpg")">
                    </div>
                    <div class="team-content">
                        <h3 class="title">@Html.ActionLink("حذف صنف", "Del_cat", null, new { @class = "title" })</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/add_offer.jpg")">
                    </div>
                    <div class="team-content">
                        <h3 class="title">@Html.ActionLink(" عرض جديد", "create_offer_list", null, new { @class = "title" })</h3>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/delete_offer.jpg")">
                    </div>
                    <div class="team-content">
                        <h3 class="title">@Html.ActionLink("إلغاء عرض", "delete_offer", null, new { @class = "title" })</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="our-team">
                    <div class="pic">
                        <img src="@Url.Content("~/images/user.png")">
                    </div>
                    <div class="team-content">
                        @Html.ActionLink("تقارير الزبائن", "reports_list", null, new { @class = "title" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Stuff -->

FFR/Views/Management/add.cshtml
@model FFR.Models.category

@{
    ViewBag.Title = "إضافة صنف";
}

<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>إضافة صنف</h1>
            </div>
        </div>
    </div>
</div>
<div class="stuff-box">
    <div class="container">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal text-right" dir="rtl">
            @if (ViewBag.message != null)
            {
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    @ViewBag.message
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <p class="control-label col-md-2">أدخل اسم الصنف</p>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="إضافة" class="btn btn-success" />
                </div>
            </div>
        </div>
        }
        <div class="text-right" dir="rtl">
            @Html.ActionLink("العودة لصفحة الإدارة", "Index")
        </div>
    </div>
</div>

FFR/Views/Management/create_offer.cshtml
@model FFR.Models.meal

@{
    ViewBag.Title = "إنشاء عرض";
}

<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>إنشاء عرض</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->
<!-- Start Stuff -->
<div class="stuff-box">
    <div class="container text-right" dir="rtl">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @if (ViewBag.message != null)
            {
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    @ViewBag.message
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", disabled = "true" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <P class="control-label col-md-2">السعر </P>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control", disabled = "true" } })
                    @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <P class="control-label col-md-2">السعر للخصم</P>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.discount_price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.discount_price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="حفظ" class="btn btn-primary" />
                </div>
            </div>
        </div>
        }

        <div>
            @Html.ActionLink("العودة لقائمة إضافة عرض", "create_offer_list")
        </div>
    </div>
</div>

FFR/Views/Management/reports_list.cshtml
@model IEnumerable<FFR.Models.customer>

@{
    ViewBag.Title = "الزبائن";
}

<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>الزبائن</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->
        <!-- Start blog -->
<div class="blog-box">
    <div class="container text-right"dir="rtl">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>قائمة الزبائن</h2>
                    <p>يمكنك الضغط على زر استعراض لرؤية تفاصيل الزبون والوجبات التي يفضلها والتي يطلبها</p>
                </div>
            </div>
        </div>
        <div class="row">

            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="blog-box-inner">
                        <div class="blog-img-box">
                            <img class="img-fluid" src="@Url.Content("~/images/user.png")" alt="">
                        </div>
                        <div class="blog-detail">
                            <h4> الاسم: @Html.DisplayFor(modelItem => item.name) </h4>
                            <ul>
                                <li><span>رقم الهاتف: @Html.DisplayFor(modelItem => item.phone)</span></li>
                            </ul>
                            <p>العنوان: @Html.DisplayFor(modelItem => item.address)</p>
                            <br /><br /><p>يمكنك الضغط على زر استعراض لرؤية المزيد من التفاصيل عن الزبون</p><br />
                            @using (Html.BeginForm("report", "Management", FormMethod.Post))
                            {
                                <input type="submit" name="@item.Id" id="@item.Id" value="استعراض" class="btn btn-lg btn-circle btn-outline-new-white" />
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>